// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lyPd4-tB55AP8ENJ9egiew6dFvragZs',
    appId: '1:279874668558:web:7f3df86b017e9bfc56d45f',
    messagingSenderId: '279874668558',
    projectId: 'zar-zamin',
    authDomain: 'zar-zamin.firebaseapp.com',
    storageBucket: 'zar-zamin.appspot.com',
    measurementId: 'G-YGLD5XCQRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2cMQhKnhEQ4t3S6g9840WfDOu4yHYtU',
    appId: '1:279874668558:android:8a21f73f96fe6fed56d45f',
    messagingSenderId: '279874668558',
    projectId: 'zar-zamin',
    storageBucket: 'zar-zamin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_ah95N7xJmLIuGzjD33X6M4pZzcnnno',
    appId: '1:279874668558:ios:13891d5aee5590ec56d45f',
    messagingSenderId: '279874668558',
    projectId: 'zar-zamin',
    storageBucket: 'zar-zamin.appspot.com',
    iosBundleId: 'com.example.zarZaminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_ah95N7xJmLIuGzjD33X6M4pZzcnnno',
    appId: '1:279874668558:ios:13891d5aee5590ec56d45f',
    messagingSenderId: '279874668558',
    projectId: 'zar-zamin',
    storageBucket: 'zar-zamin.appspot.com',
    iosBundleId: 'com.example.zarZaminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2lyPd4-tB55AP8ENJ9egiew6dFvragZs',
    appId: '1:279874668558:web:6dfce18bb5aa7cae56d45f',
    messagingSenderId: '279874668558',
    projectId: 'zar-zamin',
    authDomain: 'zar-zamin.firebaseapp.com',
    storageBucket: 'zar-zamin.appspot.com',
    measurementId: 'G-8HKLBLM0VW',
  );
}
